import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "@/app/_styles/globals.css";
import { DarkModeProvider } from "./_contexts/DarkModeContext";
import { AsideContextProvider } from "./_contexts/AsideContext";
import Main from "./_components/ui/Main";

const plus_Sans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plus_Sans.className}>
        <DarkModeProvider>
          <AsideContextProvider>
            <Main>{children}</Main>
          </AsideContextProvider>
        </DarkModeProvider>
      </body>
    </html>
  );
}
